# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e55374ff885cad4febe4a0668d20c1d9b7aa75cc3fc977e88fe5eb69759e39b36d700eb3086a1a1a74dad7006fe6ae866809ab424119808fc11d04997a8271cd

test:
  secret_key_base: d1e83849956fa1e32dc3c2fcccb15a214c365a5d802c2ad59babc79262de380afe629f847549feaae6834f4e1a94d52795019f635e4e4d1db132e4f3582106ca

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
